config/routes.rb
Rails.application.routes.draw do
  

  root controller: :home, action: :index

  resource :events, only: [] do
    get :nearby, defaults: { format: :xml }
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  layout "kml"

  def nearby
    @map_filter_form = MapFilterForm.build
    @map_filter_form.attributes = map_filter_form_params

    if @map_filter_form.valid?
      respond_to :xml
    else
      head :unprocessable_entity
    end
  end

  private
  def map_filter_form_params
    params.require(:map_filter_form).permit(:latitude, :longitude, :start_datetime, :end_datetime, :keywords, :minus_keywords, :radius, :min_attendees)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    #@map_filter_form = MapFilterForm.build
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/events/nearby.xml.erb
<%= cache "/nearby/#{@map_filter_form.to_query}", expires_in: 24.hours, skip_digest: true do %>
  <% @map_filter_form.events.each do |event| %>
    <% if event["venue"].present? %>
      <Placemark id="<%= event["id"] %>">
        <name><%= event["name"] %></name>
        <description>
          <![CDATA[
            <p><%= event["name"] %></p>
            <p><font><%= Time.at(event["time"].to_i / 1000) %></font></p>
            <p>Guests: <%= event["yes_rsvp_count"] %></p>
            <p><%= link_to event["group"]["name"], event["event_url"], targer: "_blank" %></p>
            <%#= (event["description"] || "").html_safe %>
          ]]>
        </description>
        <Point>
          <coordinates><%= event["venue"]["lon"] %>,<%= event["venue"]["lat"] %></coordinates>
        </Point>
      </Placemark>
    <% end %>
  <% end %>
<% end %>

app/views/forms/_map_filter_form.html.erb
<%= bootstrap_form_for MapFilterForm.build, url: "#" do |f| %> 
  <%= f.hidden_field :latitude, step: "0.0001", max: "90", min: "-90", class: "session-store"  %>
  <%= f.hidden_field :longitude, step: "0.0001", max: "180", min: "-180", class: "session-store" %>
  <%= link_to "🌐 Locate Me", "#", class: "locate-me btn btn-default" %>
  <hr />
  <%= f.datetime_field :start_datetime %>
  <%= f.datetime_field :end_datetime %>
  <hr />
  <%= f.text_field :keywords, class: "session-store" %>
  <%= f.text_field :minus_keywords, class: "session-store" %>
  <%= f.number_field :radius, min: 1, max: 100, help: "In Miles", class: "session-store" %>
  <%= f.number_field :min_attendees, class: "session-store" %>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/home/_gmap.html.erb
<div id="gmap" class="gmap" data-kml-url="<%= nearby_events_url %>"></div>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCptR5wMn-Idk7kh2bgaOpa-8oPZcTnOzk&callback=initGMap" async defer></script>

app/views/home/index.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-3">

    <%= render "forms/map_filter_form" %>

  </div>
  <div class="col-xs-12 col-sm-9">

    <%= render "home/gmap" %>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MeetupMap</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="container">
      <div class="row">
        <div class="col-xs-12 col-md-6">
          <h1>MeetupMap - Lists suck!</h1>
        </div>
        <div class="col-xs-12 col-md-6">
          <iframe src="https://rcm-eu.amazon-adsystem.com/e/cm?o=2&p=42&l=ur1&category=consumerelectronics&banner=0QZRBB0GNMSP1X9DKG02&f=ifr&linkID=d7ca835d560eeb1b55c10743e0a9c7f5&t=fulondes-21&tracking_id=fulondes-21" width="234" height="60" scrolling="no" border="0" marginwidth="0" style="border:none;" frameborder="0" class="f-right mt-3 mb-3"></iframe>
        </div>
      </div>
    </header>

    <main class="container">
      <%= yield %>
    </main>

    <footer class="container">
      <!--<p>I made this!</p>-->
    </footer>

    <%= render 'shared/levelsio_by' %>
  </body>
</html>

app/views/layouts/kml.xml.erb
<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://earth.google.com/kml/2.2">
  <Document>
    <name>Meetup Events</name>

    <Style id="paddle">
      <IconStyle>
        <Icon>
          <href>http://maps.google.com/mapfiles/kml/paddle/wht-blank.png</href>
        </Icon>
      </IconStyle>
    </Style>

    <%= yield %>

  </Document>
</kml>

app/views/shared/_levelsio_by.html.erb
<%= link_to 'https://twitter.com/MikeRogers0', target: '_blank', rel: 'noopener', class: 'levelsio-by' do %>
  <span>Made by</span>
  <%= image_tag 'https://mikerogers.io/images/mike-rogers-tiny.jpg', alt: 'Photo of Mike on a Snowmobile' %>
  <span class="maker">Mike Rogers</span>
<% end %>